var Events = {

    Concert:[
        {id:'concert0', feature_name:'Macklemore at KeyArena', feature: true, name: 'Macklemore and Ryan Lewis', date: 'December 10th, 2013', time: '8:00 PM', address: 'Key Arena 305 Harrison St, Seattle, WA 98109', url: 'http://www.stubhub.com/macklemore-tickets/macklemore-seattle-key-arena-11-12-2013-4316382/', pic: 'http://www.kvsc.org/userfiles/image/Macklemore.jpg'},
        {id:'concert1', name: 'Macklemore and Ryan Lewis', date: 'December 11th, 2013', time: '8:00 PM', address: 'Key Arena 305 Harrison St, Seattle, WA 98109', url: 'http://www.stubhub.com/macklemore-tickets/macklemore-seattle-key-arena-11-12-2013-4316382/' , pic: 'http://www.kvsc.org/userfiles/image/Macklemore.jpg'},        
        {id:'concert2', name: 'Macklemore and Ryan Lewis', date: 'December 12th, 2013', time: '8:00 PM', address: 'Key Arena 305 Harrison St, Seattle, WA 98109', url: 'http://www.stubhub.com/macklemore-tickets/macklemore-seattle-key-arena-11-12-2013-4316382/' , pic: 'http://www.kvsc.org/userfiles/image/Macklemore.jpg'},
        {id:'concert3', feature_name:'BOTDF at Studio Seven', feature: true, name: 'Blood on the Dance Floor', date: 'December 13th, 2013', time: '6:30 PM', address: '110 S Horton St, Seattle, WA', url: 'http://www.stubhub.com/blood-on-the-dance-floor-tickets/blood-on-the-dance-floor-seattle-studio-seven-13-12-2013-4354537/', pic: 'http://userserve-ak.last.fm/serve/500/63385367/Blood+On+The+Dance+Floor+Lovesucks.jpg'},
        {id:'concert4', name: 'Built to Spill', date: 'December 28th, 2013', time: '8:00 PM', address: '925 E Pike St, Seattle, WA', url: 'http://www.stubhub.com/built-to-spill-tickets/built-to-spill-seattle-neumos-28-12-2013-4363172/', pic: 'http://elevenmusicmag.com/wp-content/uploads/2010/07/BTS.jpg'},
        {id:'concert5', name: 'Chance the Rapper', date: 'December 15th, 2013', time: '8:00 PM', address: '1700 1st Ave S, Seattle, WA', url: 'http://www.stubhub.com/chance-the-rapper-tickets/chance-the-rapper-seattle-showbox-sodo-15-12-2013-4396800/', pic: 'http://s3.amazonaws.com/rapgenius/chance-the-rapper1.jpg'},
        {id:'concert6', feature_name:'Heart at Benaroya Hall', feature: true, name: 'Heart', date: 'December 12th, 2013', time: '7:30 PM', address: '200 University St, Seattle, WA', url: 'http://www.stubhub.com/heart-tickets/heart-and-friends---home-for-the-holidays-seattle-benaroya-hall-12-12-2013-4355394/', pic: 'http://www.thewimn.com/wp-content/uploads/2013/04/heart.jpg'},
        {id:'concert7', name: 'Give Up the Ghost', date: 'December 14th, 2013', time: '8:00 PM', address: '109 Eastlake Ave E, Seattle, WA', url: 'http://www.vividseats.com/concerts/give-up-the-ghost-tickets/give-up-the-ghost-el-corazon-12-14-1516438.html', pic: 'http://www.deathwishinc.com/files/minigutgweredownhi.jpg'},
        {id:'concert8', name: 'I Like Science', date: 'December 19th, 2013', time: '8:30 PM', address: '109 Eastlake Ave E, Seattle, WA', url: 'http://www.etix.com/ticket/online/performanceSearch.jsp?performance_id=1771840&cobrand=elcorazonseattle', pic: 'http://www.etix.com/venueResources/performer/ticket/2868/16611'},
        {id:'concert9', feature_name:'ReignWolf at Neptune Theatre', feature: true, name: 'ReignWolf', date: 'December 28th, 2013', time: '9:00 PM', address: '1303 NE 45th St, Seattle, WA', url: 'http://purchase.tickets.com/buy/TicketPurchase?pid=7612399', pic: 'http://www.ssgmusic.com/wp-content/uploads/2012/09/IMG_2332.jpg'},        
        {id:'concert10', name: 'The Blind Boys of Alabama', date: 'December 17th, 2013', time: '7:30 PM', address: '200 University St, Seattle, WA', url: 'http://www.stubhub.com/blind-boys-of-alabama-tickets/the-blind-boys-of-alabama-seattle-benaroya-hall-17-12-2013-4337747/', pic: 'http://americanthings.files.wordpress.com/2010/01/blind-boys-by-2-bp-blogspotdotcom.jpg'},
        {id:'concert11', name: 'Paul Oakenfold', date: 'December 21st, 2013', time: '9:00 PM', address: '2218 Western Ave #100, Seattle, WA', url: 'http://www.stubhub.com/paul-oakenfold-tickets/paul-oakenfold-seattle-foundation-nightclub-21-12-2013-4374926/', pic: 'http://tmobile.net-genie.co.uk/siteimage/scale/800/600/36648.png'},
        {id:'concert12', name: 'Hedwig and the Angry Inch', date: 'December 22nd, 2013', time: '7:00 PM', address: '1932 2nd Ave, Seattle, WA', url: 'http://purchase.tickets.com/buy/TicketPurchase?orgid=30247&group_id=494493&schedule=list', pic: 'http://www.nothingnewtreasures.com/wp-content/uploads/2012/06/o2m8rnko3u0goku8.jpg'},
        {id:'concert13', name: 'Natalie Cole', date: 'December 20th, 2013', time: '8:30 PM', address: '2024 E 29th St, Tacoma, WA', url: 'http://www.stubhub.com/natalie-cole-tickets/natalie-cole-tacoma-emerald-queen-casino-20-12-2013-4305530/', pic: 'http://www.israbox.com/uploads/posts/2009-07/1247843404_natalie_cole-the_best_of_natalie_cole.jpg'},
        {id:'concert14', name: 'Beethovens 9th Symphony', date: 'December 29th, 2013', time: '2:00 PM', address: '200 University St, Seattle, WA', url: 'http://www.seattlesymphony.org/symphony/buy/single/selectmethod.aspx?id=14067&src=t', pic: 'http://www.bach-cantatas.com/Pic-Bio-BIG/Seattle-Symphony-05[2009].jpg'},     
    ],
    Education:[
        {id:'education0', feature_name:'Michael Young Lecture', feature: true, name: "The Atlantic's 'View from the Top' Featuring Michael K. Young, President of the University of Washington", date: "December 5th, 2013", time: "7pm to 8:30am", address: "Four Seasons Hotel - Cypress Room 99 Union St.Seattle, WA 98161 ", url: "http://www.theatlantic.com/sponsored/delta-view-from-the-top/", pic: "http://s.huffpost.com/contributors/michael-k-young/headshot.jpg"},
        {id:'education1', feature_name:'College Admissions Seminar', feature: true, name: "Free Ivy League Admissions Seminar", date: "December 9th, 2013", time: "7pm to 8:30pm", type: "Educations",address: "Miller Community Center 330 19th Ave. E Seattle, WA 98122 ", url: "http://events.seattlepi.com/seattle_wa/events/show/368592061-free-ivy-league-admissions-seminar", pic: "http://theivycoach.com/wp-content/uploads/2011/04/Ivy-League-Admissions.png"},
        {id:'education2', feature_name:'Lean Coffee Seattle', feature: true, name: "Lean Coffee Seattle, Agile and Lean", date: "December 11th, 2013", time: "8:30am to 10:00am", type: "Educations", address: "kakao Westlake Ave N Seattle, WA 98109", url: "http://seattle.leancoffee.org/", pic: "http://seattle.leancoffee.org/files/2013/08/lean-coffeee-visual-notes-8-14-13.png"},
        {id:'education3', feature_name:'Doing Science!', feature: true, name: "Doing Science in the Open, Michael Nielsen", date: "December 12th, 2013", time: "8:30am to 10:00am", type: "Educations", address: "University of Washington Seattle Campus Seattle, WA 98195 EE105", url: "https://www.cs.washington.edu/htbin-post/mvis/mvis?ID=1066", pic: "http://theamazingworldofpsychiatry.files.wordpress.com/2012/08/open-science.jpg"},
        {id:'education4', name: "Girls' Day", date: "December 14th, 2013", time: "10:30am to 2:00pm", type: "Educations", address: "Computer Clubhouse of Tacoma 1209 Martin Luther King Jr. Way Tacoma, WA 98415", url: "http://calendar.thenewstribune.com/tacoma_wa/events/show/349046343-girls-day", pic: "img/girl.jpg"},        
        {id:'education5', name: "Introduction to Meditation", date: "Everyday", time: "6:30pm to 8:00pm", type: "Educations", address: "insideout yoga studio 8016 Dayton Ave. N", url: "http://www.ioystudio.com/workshops2.html", pic: "img/zen.jpg"},       

    ],
    Sports: [
        {id:'sports0', name: "WWE Monday Night Raw", date: "December 9th, 2013", time: "4:30pm", address: "Key Arena 305 Harrison St, Seattle, WA 98109", url: "http://www.ticketmaster.com/WWE-Monday-Night-RAW-tickets/artist/836344", pic: "http://www.seattleweekly.com/csp/mediapool/sites/dt.common.streams.StreamServer.cls?STREAMOID=OK8JvD7zGlLNEihg7P$aIc$daE2N3K4ZzOUsqbU5sYtAxdsTUga2fqAO$5aTXdgMWCsjLu883Ygn4B49Lvm9bPe2QeMKQdVeZmXF$9l$4uCZ8QDXhaHEp3rvzXRJFdy0KqPHLoMevcTLo3h8xh70Y6N_U_CryOsw6FTOdKL_jpQ-&CONTENTTYPE=image/jpeg"},
        {id:'sports1', name: "Idaho State Bengals at Washington Huskies", date: "December 14th, 2013", time: "1:00pm", address: "Alaska Airlines Arena 3870 Montlake Blvd NE, Seattle, WA 98105", url: "http://www.stubhub.com/university-of-washington-basketball-tickets/washington-vs-idaho-state-12-14-2013-4353564/", pic: "https://pbs.twimg.com/media/Ba3EwJTCAAATX2r.jpg:large"}, 
        {id:'sports2', name: "South Alabama Jaguars at Gonzaga Bulldogs", date: "December 14th, 2013", time: "7:00pm", address: "Key Arena 305 Harrison St, Seattle, WA 98109", url: "http://www.stubhub.com/university-of-washington-basketball-tickets/washington-vs-idaho-state-12-14-2013-4353564/", pic: "http://searchingforbillyedelin.files.wordpress.com/2009/01/gonzaga1.jpg?w=450&h=450"},
        {id:'sports3', feature_name:'NCAA Volleyball Championship', feature: true, name: "NCAA Women’s Volleyball Championship – All Sessions", date: "December 19th, 2013", time: "All Day ", address: "Key Arena 305 Harrison St, Seattle, WA 98109", url: "http://www.ticketmaster.com/event/0F004974B80826AD?artistid=951211&majorcatid=10004&minorcatid=204", pic: "http://img.bleacherreport.net/img/images/photos/002/039/966/hi-res-5504812_crop_exact.jpg?w=1500&h=1500&q=85"},
        {id:'sports4', feature_name:'Uconn Huskies @ UW Huskies', feature: true, name: "UConn Huskies at Washington Huskies", date: "December 22th, 2013", time: "12:30pm ", address: " Alaska Airlines Arena 3870 Montlake Blvd NE, Seattle, WA 98105", url: " http://www.ticketmaster.com/UConn-Huskies-Mens-Basketball-tickets/artist/846009", pic: " http://crosscut.com/media/resized_image/story_image/husky-basketball-hoops_fit_600x600.jpg"},
        {id:'sports5', feature_name:'Cardinals @ Seahawks', feature: true, name: "Arizona Cardinals at Seattle Seahawks", date: "December 22th, 2013", time: "1:05pm ", address: "Century Link Field 800 Occidental Ave S, Seattle, WA 98134", url: " http://www.stubhub.com/cardinals-seahawks/?isGen3=1", pic: "http://img.bleacherreport.net/img/images/photos/002/553/187/hi-res-158266274-tight-end-anthony-mccoy-of-the-seattle-seahawks-rushes_crop_exact.jpg?w=1500&h=1500&q=85"},
        {id:'sports6', name: "Mississippi Valley Delta Devils at Washington Huskies", date: "December 27th, 2013", time: "7:30pm ", address: " Alaska Airlines Arena 3870 Montlake Blvd NE, Seattle, WA 98105", url: "http://www.stubhub.com/university-of-washington-basketball-tickets/washington-vs-mississippi-valley-state-12-27-2013-4353566/", pic: " http://www.docsports.com/images/lib/large/abdul-gaddy.jpg"},
        {id:'sports7', feature_name:'Rams @ Seahawks', feature: true, name: "St. Louis Rams at Seattle Seahawks", date: "December 29th, 2013", time: "1:25pm ", address: "Century Link Field 800 Occidental Ave S, Seattle, WA 98134", url: " http://www.ticketmaster.com/Seattle-Seahawks-tickets/artist/806020", pic: "https://fbcdn-sphotos-a-a.akamaihd.net/hphotos-ak-frc3/p480x480/1382289_558448627559562_1156429680_n.jpg"},
        {id:'sports8', name: "Hadford Hawks at Washington Huskies", date: "December 29th, 2013", time: "6:00pm ", address: "Alaska Airlines Arena 3870 Montlake Blvd NE, Seattle, WA 98105", url: "http://www.vividseats.com/ncaab/washington-huskies-tickets/washington-12-29-1481011.html", pic: "http://www.wearejuxt.com/wp-content/uploads/2012/12/Will-Austin-iPhone-121612-10464.jpg"},

    ],
    Community: [
        {id:'community0', name: "Pike Place", date: "Everyday", time: "9:00am – 6:00pm, Sunday 9:00am – 5:00pm", address: "Pike Place Market 85 Pike Street Seatle, Washington 98101", url: "http://www.pikeplacemarket.org", pic: "http://img4-2.sunset.timeinc.net/i/2011/09/savor-the-west-pike-place-market-l.jpg?400:400"}, 
        {id:'community1', name: "Ballard Farmers Market", date: "Sundays", time: "10:00am – 3:00pm", address: "Ballard Ave At 22nd Ave Seattle, WA 98107", url: "http://www.yelp.com/biz/ballard-sunday-farmers-market-seattle", pic: "http://static.flickr.com/88/232353951_26ef1591f6.jpg"}, 
        {id:'community2', name: "West Seattle Farmers Market", date: "Sundays", time: "10:00am – 2:00pm", address: "West Seattle Farmers Market SW Alaska St, Seattle, WA ‎", url: "http://www.seattlefarmersmarkets.org/markets/west_seattle", pic: "http://seattlebloggers.com/wp-content/uploads/2013/06/West-Seattle-Farmers-Market.jpg"}, 
        {id:'community3', name: "University District Farmers Market", date: "Saturdays", time: "10:00am – 2:00pm", address: "University way NE and NE 50th st., Seattle, 98105‎", url: " http://www.seattlefarmersmarkets.org/markets/u_district", pic: "http://img4.coastalliving.com/coastal_loves/pacific-northwest-shops-university-district-farmers-market-x.jpg?500:500"}, 
        {id:'community4', name: "The Christmas Revels", date: "December 14, 2013", time: "2:00pm – 7:30pm", address: "Rialto Theater 310 S 9th St, Tacoma, WA ‎‎", url: "http://www.broadwaycenter.org/season/showDetails.asp?key=441", pic: "http://s2.evcdn.com/images/edpborder500/I0-001/015/000/937-6.jpeg_/christmas-revels-presents-thespiritsofhaddonhall-37.jpeg"}, 
        {id:'community5', name: "Fremont Sunday Street Market", date: "Sundays", time: "10:00am– 5:00pm", address: "400 N 34th St Seattle, WA 98103‎‎", url: "http://www.yelp.com/biz/fremont-sunday-street-market-seattle", pic: "http://pp3.walk.sc/s500/production/45441.jpg"}, 
        
    ]

};







